### PR TITLE
fix:Limit the amount of data visible on each time table. #102

### LINKED ISSUE #102: Limit the amount of data visible on each time table.
**Is your feature request related to a problem? Please describe.**
Too many elements are visible on each of the tables.

**Describe the solution you'd like**
Make a limitation on how much data is displayed on each graph - no more then 8 elements.

The solution of how this visibly looks like is already available to see on page: https://test.lastic.xyz/bulkcore1

However it needs to be implemented as well on pages :
 - https://test.lastic.xyz/my-cores
 - https://test.lastic.xyz/renewal
 - https://test.lastic.xyz/paraId
 
 Since this data is not fetched from graphQl and is fetched from the state and elegant solution like on the https://test.lastic.xyz/bulkcore1 won't be available, the solution will still have to fetch all the data from the state, just the user shouldn't see all the data. Have only max let's say 8 elements visible on the table.

Screenshot 2024-03-27 at 12 26 52

**Additional context**

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

### PR DESCRIPTION
**Pull request by jeevikasirwani**
**Thank you for your contribution** to the [Lastic - Blockspace markeplace](https://lastic.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix

## Context

- [ ] Closes #102 

#### Did your issue had any of the "$" label on it?

- [ ] My BTC address:

### CODE REVIEW

**Comment by poppyseedDev** [comment]
Hei @jeevikasirwani thanks for your contribution!
Please make sure all your deployment builds correctly. You can test it with pnpm run build and maybe also run pnpm run lint:fix. 

And also please implement the table buttons on other pages as well.

Quote:
```
However it needs to be implemented as well on pages :
 - https://test.lastic.xyz/my-cores
 - https://test.lastic.xyz/renewal
 - https://test.lastic.xyz/paraId
 ```

**Comment by poppyseedDev** [comment]
Problem not fixed in /paraId
Screenshot 2024-03-28 at 18 25 36

**Comment by jeevikasirwani** [comment]
i am trying to solve that part .....will revert back soon

**Comment by poppyseedDev** [comment]
I want to finish something today so I need this feature already, since it's half done we will not be paying the full amount. 

Please send you address USD-T, DOT or BTC.

**Comment by jeevikasirwani** [comment]
bc1q74266ss0hg7vcz0emxn7x377hz9fjgknlhmdah

**Comment by jeevikasirwani** [comment]
bc1q74266ss0hg7vcz0emxn7x377hz9fjgknlhmdah

**Comment by poppyseedDev** [comment]
@jeevikasirwani is this BTC?

**Comment by jeevikasirwani** [comment]
yes

**Comment by jeevikasirwani** [comment]
yup

**Comment by jeevikasirwani** [comment]
WhatsApp Image 2024-03-31 at 19 30 19

**Comment by poppyseedDev** [comment]
https://blockstream.info/tx/ff325ded48fbc88ec48491d88b32486d924f87f7d2b171a5401f1357dcfe79fe

**Comment by jeevikasirwani** [comment]
yes received thank you

**Pull request merged**
